### ISSUE TITLE
[Desktop Bug] Missing Source View Bullets | Reading View Accidental Extra Bullets

### ISSUE THREAD

**Issue by SuperDragonite2172** [ArtexJay/Obsidian-CyberGlow#46]
**Describe the bugs**
- Bullet Points are missing when viewing a note in Source mode.
- Collapsing the list has the dash reappear in Source Mode, but creates an extra bullet point in Reading Mode and stretched bullet point in Live Preview mode.

**To Reproduce**
Steps to reproduce the behaviors:
1. Create/Open a note with a list.
2. Switch to Source View to see missing bullet points.
3. Collapse bullet point to see dash return.
4. Switch to Reading View to observe extra bullet point
5. Switch to Live Preview to see stretched bullet point.

**Expected behavior**
I expected the bullet points to be visible in Source View and the extra bullets to not be there in Live Preview and Reading view.

**Screenshots**
Source:
![Source](https://user-images.githubusercontent.com/14007732/219976121-5c4bb85a-e978-4588-a80b-ac2e130b455e.png)
![Source Folded](https://user-images.githubusercontent.com/14007732/219976137-df78f1e7-52ee-45e2-b8f1-9d63af06271c.png)
Reading:
![Reading](https://user-images.githubusercontent.com/14007732/219976185-7f7d7444-d915-4b99-bdf3-e6865d1e39f9.png)
![Reading Folded](https://user-images.githubusercontent.com/14007732/219976203-e3ffd3fd-891f-40b1-a673-88101b4aa1b9.png)
Live Preview:
![Live Preview](https://user-images.githubusercontent.com/14007732/219976236-9714ec12-cca9-485d-9de4-af111860f44a.png)
![Live Preview Folded](https://user-images.githubusercontent.com/14007732/219976256-badbd6c5-cd2e-4558-82ba-205fe19b4791.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Obsidian Version: v1.1.9
 - Cyber Glow Version: v7.8.2

**Additional context**
N/A

**Comment by ArtexJay** [comment]
How do you collapse the bullet points? ._. 
Can't seem to collapse them.

Source mode is indeed missing the points, i may have accidentally removed them a while back, I think i still have them saved somewhere that i can just reintegrate.

**Comment by ArtexJay** [comment]
Done, will be included in the next update.

**Comment by SuperDragonite2172** [comment]
Thanks for the quick fix.

**Comment by ArtexJay** [comment]
update theme and check back

**Comment by SuperDragonite2172** [comment]
I've updated to 7.8.5.  Live Preview and Reading appear to be fixed.  The bullet points are still missing in Source mode.  I'm not sure if this is bug in the theme still or if I updated incorrectly.  On a whim I also checked out the icon option in Style Settings for the sidebar but it doesn't appear to change it (It's set to the Obsidian Logo by DrIcon14.  My guess as to why is because I have "Window Frame Style" set to `Obsidian` (See attached screenshot).
![Window Frame Style](https://user-images.githubusercontent.com/14007732/221328369-7bbc1e4d-2187-4c6e-8886-9d6756736bd9.png)
Let me know if you need more information.

**Comment by ArtexJay** [comment]
Oh wow I guess I accidentally removed them after I added the bullet points in the source mode🤦
I'll check it out.

For the second point, yea i've mostly tailored my theme for Window Frame Style Hidden. 
I can put a notice in the description that it will only impact Window Frame Style Hidden as of now.

**Comment by SuperDragonite2172** [comment]
That works for me.  I think the green-outline Obsidian "shard" still looks nice (although it does get replaced with the default one when I hover over it).

**Comment by ArtexJay** [comment]
> That works for me. I think the green-outline Obsidian "shard" still looks nice (although it does get replaced with the default one when I hover over it).

Not supposed to happen make a new issue, can you possibly do a video showing it or gif? Cause I haven't noticed that on my side.

**Comment by ArtexJay** [comment]
Resolved the source code issue, it will be available in the next update also noticed some misaligned dropdown chevrons for the lists and re-arranged them.

**Comment by SuperDragonite2172** [comment]
Created a new issue here (https://github.com/ArtexJay/Obsidian-CyberGlow/issues/47).  Hopefully that's what you're looking for.

**Comment by ArtexJay** [comment]
just released another update, update to v7.8.8 and check if the bullet lists are all working as they should.

**Comment by SuperDragonite2172** [comment]
I think you forgot to add the `manifest.json` and `theme.css` into the v7.8.8 release.  I just see the source code zip files instead of the separate files like with the previous update.  That said the bullet lists appear to be working as expected.  Thanks again for taking the time to fix this.  Do you want me to close the issue or do you want to handle that?

**Comment by ArtexJay** [comment]
> I think you forgot to add the `manifest.json` and `theme.css` into the v7.8.8 release. I just see the source code zip files instead of the separate files like with the previous update. That said the bullet lists appear to be working as expected. Thanks again for taking the time to fix this. Do you want me to close the issue or do you want to handle that?

Oops, uploaded them.

**Comment by SuperDragonite2172** [comment]
I just extracted the files from the source code ZIP file, I pointed it out so other users don't have to go through the same process.

**Comment by ArtexJay** [comment]
> I just extracted the files from the source code ZIP file, I pointed it out so other users don't have to go through the same process.

Yea, i just forgot to include it this time.
